### ISSUE TITLE
[Feature] Create a GoInputGroup Component

### ISSUE THREAD

**Issue by AlexOverbeck** [mobi/goponents#124] opened 2019-08-07 18:36 UTC
### What is the feature that you would like to propose?
We need a component that will give us the ability to wrap groups of inputs together much like bootstrap does.

Bootstrap input groups: https://getbootstrap.com/docs/4.3/components/input-group/

### Describe the solution you'd like
This feature will needs to have the following requirements:
1. This component will wrap a group of form inputs
2. The group of inputs will combine nicely into a rounded out super input

**Comment by grahamhency** [comment] 2020-06-02 14:47
Closing as a duplicate of #528. That issue has more detail than this.

**Closed by grahamhency** 2020-06-02 14:47 UTC
Labels: feature, new issue
