### ISSUE TITLE
goPonents Footer Component 

### ISSUE THREAD

**Issue by nilahdad** [mobi/goponents#213] opened 2019-10-01 09:26 UTC
Hi Team, I think in the basic goPonents layout we have to add footer component, currently it's missing. FYI, by default, the footer behavior should be aligned in the bottom of the browser and based on the content or page it should be floated with bottom of the content, regarding this I will raise ticket in the GitHub.
 
You can see here, in the current basic layout, this much only is available...

Simple Setup
For the sake of this example, we'll be referencing the layout of this application because it's a living example of the entire layout component and family.

app.module

  // Required imports for the layout:
  import {
    GoHeaderModule,
    GoIconButtonModule,
    GoLayoutModule,
    GoSideNavModule
  } from '@tangoe/goponents';

  @NgModule({
    declarations: [
      AppComponent
    ],
    imports: [
      GoHeaderModule,
      GoIconButtonModule,
      GoLayoutModule,
      GoSideNavModule
    ],
    bootstrap: [AppComponent]
  })
  export class AppModule { }
  
app.component

  <go-layout>
    <go-header go-layout-header>
      
    </go-header>
    <go-side-nav go-layout-nav>
      
    </go-side-nav>
  </go-layout>

**Comment by grahamhency** [comment] 2019-10-01 12:27
Duplicate of #164

**Closed by grahamhency** 2019-10-01 12:27 UTC
Labels: feature, new issue
