### ISSUE TITLE
[BUG] Header Bar Buttons Jump when navigating across pages with Header Bars

### ISSUE THREAD

**Issue by Fagiolia1** [mobi/goponents#524] opened 2020-03-24 16:13 UTC
**Describe the bug**
When navigating between pages with header bar buttons, the buttons on the header bar jump from left to right once the page fully loads.

**To Reproduce**
1. Go to a page with a header bar and some buttons.
2. Navigate to another page with header and buttons.
3. Watch the buttons move from the right to fully right aligned once the page loads.

**Expected behavior**
The buttons should not be jumping between page loads

**Screenshots**
![image](https://user-images.githubusercontent.com/8883257/77449791-cbe6aa80-6dc8-11ea-8b49-209efa908b50.png)

**Comment by grahamhency** [comment] 2020-06-02 19:20
@mobi/global-goponents-devs, @mobi/tangoe-ux-ui I cannot seem to replicate this issue in Goponents and the `mobi` app does not yet use this. Can any of you provide an example of where this is happening?

**Comment by kpmurphh** [comment] 2020-06-04 19:54
@grahamhency I can't replicate it either. I tried a few different ways in the cloud app (where Andy took these screenshots) and everything looked fine. The cloud team also hasn't reported it as a bug so I'm hoping it was fixed indirectly. If it does come up I will definitely let you know.

**Comment by grahamhency** [comment] 2020-06-05 14:52
Hmm. I think @eligolding was able to recreate it. He reached out to me, any chance you could provide some insight here @eligolding?

**Comment by Fagiolia1** [comment] 2020-06-05 15:01
@grahamhency @kpmurphh Jason was able to recreate it a few times. You should be able to recreate it within Cloud by navigating from a page that has a header bar to another page with a header bar. 

See if Jason has an example as well. He saw something similar in Telecom.

**Comment by kpmurphh** [comment] 2020-06-05 15:37
Hey @cosmicdust73 do you know where we can replicate this?

**Comment by eligolding** [comment] 2020-06-05 16:50
I reproduced it by clicking on a link to an account from the invoice page in Cloud.

**Comment by grahamhency** [comment] 2020-06-08 14:54
I will look into this and see if maybe I can recreate in the style guide.

**Comment by grahamhency** [comment] 2020-06-11 18:03
@eligolding, @mobi/tangoe-ux-ui I found the culprit for this and I've got a fix up in a PR. Turns out it revolved around a routing animation being applied to the header bar.

**Comment by eligolding** [comment] 2020-06-11 18:20
![ ](https://media.giphy.com/media/xT5LMFEB6Z6DADQBP2/giphy.gif)

**Comment by grahamhency** [comment] 2020-06-12 16:45
Closed with #585

**Closed by grahamhency** 2020-06-12 16:45 UTC
Labels: bug, work in progress
